[book]
authors = ["Jaroslaw Nowosad"]
language = "en"
multilingual = false
src = "doc"
title = "Technology Insights - 2022"

[output.html]
mathjax-support = true
additional-js = ["mermaid.min.js", "mermaid-init.js"]


[output.html.playground]
editable = true

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

