# Time series research papers



## Graph


https://www.connectedpapers.com/main/dcc9308f2b9879e9fecff30108faa544d977a73c/A-Framework-for-Pattern-Mining-and-Anomaly-Detection-in-Multi%20dimensional-Time-Series-and-Event-Logs/graph




## A Framework for Pattern Mining and Anomaly Detection in Multi-dimensional Time Series and Event Logs


In the present-day, sensor data and textual logs are generated by many devices. Analysing these time series data leads to the discovery of interesting patterns and anomalies. In recent years, numerous algorithms have been developed to discover interesting patterns in time series data as well as detect periods of anomalous behaviour. However, these algorithms are challenging to apply in real-world settings. We propose a framework, consisting of generic transformations, that allows to combine state-of-the-art time series representation, pattern mining, and pattern-based anomaly detection algorithms. Using an early- or late integration our framework handles a mix of multi-dimensional continuous series and event logs. In addition, we present an open-source, lightweight, interactive tool that assists both pattern mining and domain experts to select algorithms, specify parameters, and visually inspect the results, while shielding them from the underlying technical complexity of implementing our framework.



https://lirias.kuleuven.be/bitstream/123456789/642650/2/ECMLPKDD_workshop_manuscript.pdf

![](https://d3i71xaburhd42.cloudfront.net/00ced98edc1f87eb4bc8e8bf8441aec23a6be286/3-Figure1-1.png)

image::https://d3i71xaburhd42.cloudfront.net/00ced98edc1f87eb4bc8e8bf8441aec23a6be286/3-Figure1-1.png[]

![](https://d3i71xaburhd42.cloudfront.net/00ced98edc1f87eb4bc8e8bf8441aec23a6be286/4-Figure2-1.png)

image::https://d3i71xaburhd42.cloudfront.net/00ced98edc1f87eb4bc8e8bf8441aec23a6be286/4-Figure2-1.png[]

![](https://d3i71xaburhd42.cloudfront.net/00ced98edc1f87eb4bc8e8bf8441aec23a6be286/8-Figure3-1.png)

image::https://d3i71xaburhd42.cloudfront.net/00ced98edc1f87eb4bc8e8bf8441aec23a6be286/8-Figure3-1.png[]


![](https://d3i71xaburhd42.cloudfront.net/00ced98edc1f87eb4bc8e8bf8441aec23a6be286/10-Figure4-1.png)

image::https://d3i71xaburhd42.cloudfront.net/00ced98edc1f87eb4bc8e8bf8441aec23a6be286/10-Figure4-1.png[]


