# WAX


The Worldwide Asset eXchange™ (WAX) is the world's most proven and eco-friendly blockchain for NFTs, video games and collectibles.





Create NFT!


https://wax-io.medium.com/the-ultimate-guide-how-to-create-nfts-on-wax-bdf94fea64d0




====
COPY:




## The Ultimate Guide: How To Create NFTs on WAX
This guide shows you how to turn your static images, GIFs, music files, and videos into NFTs on WAX.

Creating NFTs on WAX is really simple. All you need to get started is a WAX Cloud Wallet Account. All steps shown in this guide also work using a self-managed WAX Blockchain Account using Scatter or Anchor.

### Let’s get started

The simplest way to create your first NFT on WAX is using AtomicHub’s convenient NFT Creator. Log in using your WAX Cloud Wallet or one of the other options at https://wax.atomichub.io/creator.

### Details of your first NFT Collection

Click “Create New Collection”
Add a collection photo. Pro tip: using an image that has a transparent background looks more appealing.
Enter your collection name. Pick a meaningful name that describes your collection best. This one needs to be exactly 12 characters long.
Enter a display name for your collection. On this, you have creative freedom. Pick whatever you want.
Got a website, Twitter profile, or anything else that’s related to your collection? Make sure to let collectors know and fill out the “Website URL” input.
What is your new collection all about? What do you want collectors to know? Enter a collection description.
Set a market fee. The percentage you enter here is what YOU will earn every time your NFTs in this collection sell on ANY WAX-powered secondary market.
Once you’re done, click “Create Collection” and confirm the transaction that pops-up in a new window.

### It’s time to create your first “Schema”

A schema is being used to have a layout for your NFTs. It’s like creating a Series within your collection. For example, deadmau5 is the collection name, and series1 is what his schema is called. A schema name can be 12 characters long.
What attributes should your NFT have besides the name & image? These are your file/format options:

* img = Primary image of your NFT (Type: Image)
* backimg = Secondary image of your NFT (Type: Image)
* video = Displays your NFT in a video format (Type: IPFS)
* audio = Displays your NFT in an audio format (Type: IPFS)

Make sure to pick the right “Attribute Type,” once confirmed, you can NOT edit this. Already fat-fingered? No worries, only filled-out attribute inputs are being displayed later. Add what you intended to add. You can also add more attributes. Later on, this will not update already minted NFTs.
The final step we’ve all been waiting for: Minting your first NFT!
Once your schema is created, click the “Mint New Asset” button. Here’s how you do it, step by step:
Upload your file by clicking “Add an image”
Is your file larger than 2MB? Upload your files directly to IPFS using pinata.cloud. Create an account, upload your file and enter the IPFS Hash manually as shown here:

IPFS Hash Example: Qmaaqz4cVoDZnKMAVEGEYrCvEEiq4vmnD5P7PvoWJ6ZTni
The image preview will immediately show up on AtomicHub.
2. Fill out other attribute inputs. What’s the title & description of your NFT? Does it have any other files you want to attach? This is the time to make sure everything is correct. Once minted, you cannot alter it.

Templates will make your life easier. Try it.
Do you want to create NFTs on a larger scale? Try Templates! Navigate back to your schema and create a template that can be used later on to mint NFTs on-demand without having to enter the title, image hashes, and description every time. Once your template is ready, go back to “Mint New Asset” and pick it from the drop-down menu.
Make sure to check out the “Basic WAX Account Management Guide” linked below.

Other links you might find useful:

What is IPFS? go.wax.io/IPFS

Beginner’s Guide to NFTs: https://go.wax.io/NFT-Beginners-Guide

Basic WAX Account Management: https://go.wax.io/Account-Management

Check out this series of video guides by CryptoStache:

Beginners:

Advanced:

*UPDATE: For mp4’s to work you must create an “IPFS” attribute for your schema, along with a secondary Image attribute as well. If you don’t have both an IPFS & 2nd image attribute filled in, the mp4 will not show.
Share your thoughts on WAX Community Channels:

Discord: go.wax.io/Discord

Twitter: go.wax.io/Twitter

Website: wax.io




